/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MistSensor, MistSensor, AUTO)


PB_BIND(AirSensor, AirSensor, AUTO)


PB_BIND(LightSensor, LightSensor, AUTO)


PB_BIND(SensorQuery, SensorQuery, AUTO)


PB_BIND(Command, Command, AUTO)


PB_BIND(TimeSync, TimeSync, AUTO)


PB_BIND(SleepCycle, SleepCycle, AUTO)


PB_BIND(ACK, ACK, AUTO)


PB_BIND(NACK, NACK, AUTO)







